### ISSUE TITLE
Event ID shown

### ISSUE THREAD

**Issue by NelisV** [ECFMP/flow#219]
( Submitted by Paul Ferraz on discord )

"If i create a flow measure and select an event that doesn't involve my FIR, an ID is shown (I guess id for the event creator FIR)"

![image](https://user-images.githubusercontent.com/42404718/182033980-d8a0bf2d-8ed7-4c04-b316-d19a997c9ed7.png)

**Comment by KHardern** [comment]
1) Current behaviour is good. When Bob creates a measure EGTT is pre-selected
2) When Henk creates a measure, do not pre-select (on the basis he doesn't have EGTT assigned)
3) FIR is mandatory, always.

Continuing your story time:
> Trent [EISN, BIRD] has NMT/system permissions and has FIRs assigned EISN and BIRD
> Agamemnon [EGTT, BIRD] has NMT/system permissions and has FIRs assigned EGTT, BIRD

When Trent creates a measure, behaviour is the same as Henk. No pre-selection (on the basis he does not have EGTT assigned, even though he could select it)

When Agamemnon creates a measure, behaviour is the same as Bob, because EGTT is one of his allocated FIRs.
